apiVersion: v1
kind: Service
metadata:
  name: maven-app-service
  labels:
    app: maven-app-app
spec:
  type: NodePort
  selector:
    app: maven-app-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
